name: summer_escape
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  url_launcher: ^5.5.1

  #camera
  gallery_saver: ^2.0.1 #save images to Gallery
  image_picker: ^0.6.7+4 #pick image from Gallery
  tflite: ^1.1.1 #machine learning (tflite files)

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
    - assets/

  fonts:
    - family: Shrikhand
      fonts:
        - asset: fonts/Shrikhand-Regular.ttf
    - family: CarterOne
      fonts:
        - asset: fonts/CarterOne-Regular.ttf